trigger: none

stages:
- stage: 'buildstage'
  jobs:
  - job: 'buildjob'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - bash: |
        # Pull the Nginx Docker image (or replace with an image suitable for testing)
        sudo docker pull influxdb
        # Run the Nginx container
        sudo docker run -d -p 80:80 influxdb
      displayName: 'Pull and Run Nginx Container'

    - bash: |
        sudo chmod -R 777 ./
        sudo docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -t http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):80 -x xml_report.xml

      displayName: 'Owasp Container Scan'

    - powershell: |
        # Check PowerShell Core version
        pwsh --version

      displayName: 'PowerShell Script'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      inputs:
        testResultsFormat: 'NUnit'
        testResultsFiles: 'converted_report.xml'
