trigger: none

stages:
- stage: 'buildstage'
  jobs:
  - job: 'buildjob'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        # Pull the nginx Docker image
        sudo docker pull nginx
        # Run the nginx container
        sudo docker run -d -p 80:80 nginx
      displayName: 'Pull and Run nginx Container'

    - bash: |
        sudo chmod -R 777 ./
        sudo docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -t http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):80 -x xml_report.xml
        true
      displayName: 'Owasp Container Scan'

    - powershell: |
        Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)/s/owaspzp/"
      displayName: 'PowerShell Script'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      inputs:
        testResultsFormat: 'NUnit'
        testResultsFiles: 'converted_report.xml'