trigger: none

stages:
- stage: 'buildstage'
  jobs:
  - job: 'buildjob'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        # Pull the InfluxDB Docker image
        sudo docker pull influxdb
        # Run the InfluxDB container
        sudo docker run -d -p 80:80 influxdb
      displayName: 'Pull and Run InfluxDB Container'

    - bash: |
        sudo chmod -R 777 ./
        sudo docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -t http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):80 -x xml_report.xml
        true
      displayName: 'Owasp Container Scan'

    - powershell: |
        # Change the working directory to the location of the XSLT file
        Set-Location -Path "$(System.DefaultWorkingDirectory)/s/owaspzp/"

        # Load the XSLT file
        $XslPath = "xml_to_nunit.xslt"
        $XmlInputPath = "xml_report.xml"
        $XmlOutputPath = "converted_report.xml"
        $XslTransform = New-Object System.Xml.Xsl.XslCompiledTransform
        $XslTransform.Load($XslPath)
      displayName: 'PowerShell Script'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      inputs:
        testResultsFormat: 'NUnit'
        testResultsFiles: 'converted_report.xml'